### ISSUE TITLE
Bring back two more ADCs on RTL8720DN officially

### ISSUE THREAD

**Issue by be1ieve** [ambiot/ambd_arduino#143]
Since new boards use LOG_UART on USB connector, PB1 and PB2 are available now.
Can we officially enable A0 and A1 and only mark old BW16 model as unusable on website?

PS: Calling pinMode() and analogRead() directly on PB1 and PB2 works already.
It's just like a hidden feature for those who read datasheet.

**Comment by Aurical** [comment]
You could just directly uncomment `#define A0` and `#define A1` in the [variant.h file](https://github.com/ambiot/ambd_arduino/blob/dev/Arduino_package/hardware/variants/rtl8720dn_bw16/variant.h) for the board.

Selectively enabling it for the new board version would be much more complicated, it would require differentiating the two boards and creating a new set of pin definitions for the new board. This does not make much sense since the hardware for both boards are essentially the same.

**Comment by M-ichae-l** [comment]
Close as there is no further discussion.
