### ISSUE TITLE
can ambd support uvc cam?

### ISSUE THREAD

**Issue by chenbaijian** [ambiot/ambd_arduino#182]
as i know,ameba d support USB HIGH SPEED HOST  and  LCD controller, so it could be connectted with a USB UVC camera  and a lcd， display camera pictures on the lcd is very useful, it is used in  iot products like door bell 。 
so can this sdk support uvc cam, and transport date to lcd with dma?

**Comment by M-ichae-l** [comment]
This issue is a duplicate of [https://github.com/ambiot/amb1_arduino/issues/10](https://github.com/ambiot/amb1_arduino/issues/10)
It is being processed now. 
There is another hardware that supports video better. If you are interesting about it , please refer to [AMB82 MINI](https://www.amebaiot.com/en/ameba-arduino-summary/)
